### ISSUE TITLE
not downloadable

### ISSUE THREAD

**Issue by kurtextrem** [shortcutme/Sublime-IntelliDocs#1]
Somehow I can't manage to download this package via package control. I'm on sublime text 3. (It's not listed)
maybe because of those? http://prntscr.com/2ximbo

Also I would love to see javascript, html and css :)

**Comment by shortcutme** [comment]
Thank you for the feedback, looking after it.
Javascript/jQuery will be the next. :)

**Comment by kurtextrem** [comment]
Thanks for that quick answer, I look forward to using it :)

**Comment by shortcutme** [comment]
I think its fixed :)
https://sublime.wbond.net/packages/IntelliDocs

**Comment by jfcherng** [comment]
May I ask for C/C++ support?
The db may be enormous though...

**Comment by kurtextrem** [comment]
@shortcutme yes, works great, thank you!! :D

**Comment by shortcutme** [comment]
@jfcherng I going to add it, a created a Issue ticket for it: #2

**Comment by shortcutme** [comment]
@kurtextrem javascript/dom/jquery support added: https://github.com/shortcutme/Sublime-IntelliDocs/releases

**Comment by kurtextrem** [comment]
@shortcutme Thanks mate!
