### ISSUE TITLE
Support for set jquery syntax

### ISSUE THREAD

**Issue by pafnuty** [shortcutme/Sublime-IntelliDocs#6]
The syntax is a bit different in appearance, but the plugin works only when the javascript syntax.
It would be good to include it, and for jquery syntax.
![2014-03-06_103637](https://f.cloud.github.com/assets/1635679/2342547/7349da62-a4f9-11e3-8804-774fc72134f3.png)

**Comment by shortcutme** [comment]
@pafnuty Thanks for feedback, it should work now: https://github.com/shortcutme/Sublime-IntelliDocs/releases/tag/1.1.5

**Comment by pafnuty** [comment]
Thank you very much!
